version: '2'
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
    volumes:
      - "/Users/luis/github/clickhouse-cluster/data:/data"
      - "/Users/luis/github/clickhouse-cluster/datalog:/datalog"
  ch1:
    build:
      context: .
      dockerfile: Dockerfile.ch1
    ports:
      - 8811:8123
      - 9011:9000
    volumes:
      - "/Users/luis/github/clickhouse-cluster/ch1_volume:/var/lib/clickhouse"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "zookeeper"
    hostname: ch1
  ch2:
    build:
      context: .
      dockerfile: Dockerfile.ch2
    ports:
      - 8812:8123
      - 9012:9000
    volumes:
      - "/Users/luis/github/clickhouse-cluster/ch2_volume:/var/lib/clickhouse"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "zookeeper"
    hostname: ch2
  ch3:
    build:
      context: .
      dockerfile: Dockerfile.ch3
    ports:
      - 8813:8123
      - 9013:9000
    volumes:
      - "/Users/luis/github/clickhouse-cluster/ch3_volume:/var/lib/clickhouse"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "zookeeper"
    hostname: ch3
  ch4:
    build:
      context: .
      dockerfile: Dockerfile.ch4
    ports:
      - 8814:8123
      - 9014:9000
    volumes:
      - "/Users/luis/github/clickhouse-cluster/ch4_volume:/var/lib/clickhouse"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "zookeeper"
    hostname: ch4
  ch5:
    build:
      context: .
      dockerfile: Dockerfile.ch5
    ports:
      - 8815:8123
      - 9015:9000
    volumes:
      - "/Users/luis/github/clickhouse-cluster/ch5_volume:/var/lib/clickhouse"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "zookeeper"
    hostname: ch5
